kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-store
  namespace: code-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 60Gi