apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: gcr.io/k8s-staging-external-dns/external-dns
        imagePullPolicy: Always
        args:
        - --source=service
        - --source=ingress
        - --registry=txt
        - --policy=sync
        env:
        - name: AWS_REGION
          value: "us-east-2"
